### ISSUE TITLE
Container doesn't mount volumes

### ISSUE THREAD

**Issue by rotragit** [rb-dock8s/serviio#10]
Not sure is a docker-serviio issue, but on Ubuntu 18.04  it seems only a volume is mounted (library, in my case). If I add an explicit volume to mount (-v /data:/data) only that one is mounted and the others are not. Because the volumes all are mounted from /opt/serviio, why not mount only that? The media could me in /opt/serviio/media and all will work ok.

**Comment by ergoz** [comment]
this is how work docker and how work serviio. It is not good to mount full opt/serviio.
