### ISSUE TITLE
Hardware transcode doesn't work

### ISSUE THREAD

**Issue by AKDub** [rb-dock8s/serviio#11]
I get the following error trying to transcode with VA-API 

`[AVHWDeviceContext @ 0x7f94d1647580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': I/O error`

Both Plex and Jellyfin dockers work fine so I presume its a software issue

**Comment by ergoz** [comment]
hm... i've never see this err before. i will check it

**Comment by ergoz** [comment]
@AKDub i made a new release. Try 2.1.0 version (it should build in 30-60 minutes) and tell me is it fixed

**Comment by ergoz** [comment]
close, because no response for a long time
